[io] 
outdir: "auto"     # dir name; auto->make it based on conf params
prefix: "rp_"      # prefix for the dir name
postfix: "v23-SCLF-test-blonglin"  # postfix for the dir name

interval: 200      # output frequency in units of simulation steps for analysis files
plot_interval: 200 # QED restart freq

full_interval: -1  #output frequency to write full simulation snapshots
restart: 100000    #3800 #10000   #frequency to write restart files (these overwrite previous files)
laprestart: -1      #restart switch (-1 no restart; 0 automatic; X lap to restart)

stride: 1          #output reduce factor for fields;  NxMesh/stride must be int
stride_mom: 1      #output reduce factor for moments; NxMesh/stride must be int

mpi_task_mode: False # rank0 is empty if true


#-------------------------------------------------- 
#simulation parameters
[simulation]
cfl: 0.45      #time step in units of CFL
Nt: 30000      #150000      #maximum steps
npasses: 4     #number of current filter passes #Try 4!

qed_mode: True # QED interactions on/off
qed_step: 1    # perform QED interactions every n:th steps

qed_mode_rp = True    # Select radio pulsar interactions and settings
qed_mode_msp = False  # Select millisecond pulsar interactions and settings

#-------------------------------------------------- 
[problem]

me: -1.0        #electron mass-to-charge
mi: +1836.0     #ion mass-to-charge

chi:    0.0     # magnetic obliquity angle
bratio: 0.02    #1e-5   # nonlinearity of B field; B/B_QED
vrot:   3e-6    #0.2 # surface rotation velocity at the Rpc

Nmp:    1e12     # number of electrons/positrons in a macroparticle

delgam:  0.3     # temperature
delgam_x: 1e-3   # photon blackbody temperature in mc^2
temp_ratio: 1.0  # T_i/T_e


ninj_pairs:     30.0 #0.003 # kappa in pair injection coefficient in star
ninj_min_pairs: 0.0 # minpair inj rate per dt per cell #Try 0!

ninj_phots:     0.0 #1e3 #0 # photon injection coefficient in star
ninj_min_phots: 0.0 #0 # minphoton inj rate per dt per cell
wph: 1              # weight of atmospheric photons

jm_scaling = 1.5  #constant current scaling; equals alpha = j_m/j_co
rad_curv: 1     # curvature radius in units of polar cap radius
rad_pcap: 0.8   # gap height (fraction of box length; <1)

#--------------------------------------------------
#spatial grid parameters 
[grid]
Nx:     128 #64
Ny:     1
Nz:     1
NxMesh: 40 #80
NyMesh: 1 
NzMesh: 1 

[particles]
Nspecies: 4  # number of species (typically 2); here e^-, e^+, x
ppc: 2    # particle per cell per species
xpc: 0 #3    # photons per cell

n_test_prtcls: 100000   # number of tracer particles
max_tile_prtcl_num: 100 # maximum (plasma) prtcl count per tile (in units of n_co)
max_tile_phot_num:  100 # maximum photon count per tile (in units of n_co)


#c_omp:  30    # cells per skindepth

#--------------------------------------------------#
# QED configurations
lum_ep:  0.0  # electron injection luminosity
lum_ph1: 0.0  # fixed synchrotorn seed photon supply
lum_ph2: 0.0  # disk photon supply
 
#kTbb1: 1e-5 # soft seed photon temperature
#kTbb2: 1e-3 # disk photon tmperature

#H: 1e5       # cm characteristic size
#tau_ini: 1.0 # initial reference optical depth
#tau_ext: 0.0 # external optical depth
#
#zeta_xinj1: 0.0 # injection rate (fraction of tile reference number)
#zeta_xinj2: 0.0
#
## required weight to get lum_ph
#zeta_pinj: 0.0 # injection rate (fraction of tile reference number)
#pslope: -3.0
#pmin: 3.0
#pmax: 10.0


#--------------------------------------------------
# NOTE: unused parameters
[vmesh]
Nvx: 1
Nvy: 1
Nvz: 1

dx: 1.0 
dy: 1.0
dz: 1.0
